"""Votre message

Revision ID: 5c10fc222e87
Revises: 
Create Date: 2024-03-13 22:05:57.469683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c10fc222e87'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role_name', sa.String(), nullable=False))
    op.drop_constraint('unique_email', 'user', type_='unique')
    op.drop_constraint('unique_username', 'user', type_='unique')
    op.create_foreign_key(None, 'user', 'role', ['role_name'], ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_unique_constraint('unique_username', 'user', ['username'])
    op.create_unique_constraint('unique_email', 'user', ['email'])
    op.drop_column('user', 'role_name')
    # ### end Alembic commands ###
